apiVersion: v1
kind: Template
labels:
  template: custom-springboot-base-bc
  group: custom-springboot-base-bc
metadata:
  annotations:
    tags: custom-springboot, spring, java, spring-boot
  name: custom-springboot
parameters:
- name: APP_NAME
  description: The name of application.
  displayName: Application Name
  required: true
  value: openshift-java-base-image
- name: GIT_SOURCE_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
  value: https://github.com
- name: CONTEXT_DIR
  description: The contextDir for the application
  displayName: context Dir
  required: true
  value: .
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      runPolicy: Serial
      source:
        git:
          uri: ${GIT_SOURCE_URL}
          ref: master
        contextDir: ${CONTEXT_DIR}
      strategy:
        dockerStrategy:
          dockerFilePath: Dockerfile
      #resources:
      #  limits:
      #    cpu: 2
      #    memory: 2Gi
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      triggers:
        - type: ConfigChange
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}